#KubeJS Common Properties
#Wed Nov 05 08:02:59 EST 2025
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
serverOnly=false
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=minecraft\:purple_dye
startupErrorGUI=true
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
AdvJSExample=true
startupErrorReportUrl=
AdvJSDebug=true
